// Code generated by go generate; DO NOT EDIT.
package core

import (
    "encoding/json"
    "fmt"
    . "codeberg.org/ijnakashiar/LibreRiichi/core/game_data/tile"
)

type ActionType uint8

type ActionUnpacker struct {
    Action
}

const (
	RON ActionType = iota
	TSUMO ActionType = iota
	RIICHI ActionType = iota
	TOSS ActionType = iota
	SKIP ActionType = iota
	PON ActionType = iota
	KAN ActionType = iota
	CHII ActionType = iota
	DRAW ActionType = iota
)
func (Ron) Data() {}
func (obj Ron) MarshalJSON() ([]byte, error) {
    var raw struct {
		ActionType ActionType `json:"action_type"`
        TileToRon Tile `json:"tile_to_ron"`
        WinResult WinResult `json:"win_result"`
	}

    raw.ActionType = RON
    raw.TileToRon = obj.TileToRon
    raw.WinResult = obj.WinResult

    return json.Marshal(raw)
}

func (Tsumo) Data() {}
func (obj Tsumo) MarshalJSON() ([]byte, error) {
    var raw struct {
		ActionType ActionType `json:"action_type"`
        TileToTsumo Tile `json:"tile_to_tsumo"`
	}

    raw.ActionType = TSUMO
    raw.TileToTsumo = obj.TileToTsumo

    return json.Marshal(raw)
}

func (Riichi) Data() {}
func (obj Riichi) MarshalJSON() ([]byte, error) {
    var raw struct {
		ActionType ActionType `json:"action_type"`
        TileToRiichi Tile `json:"tile_to_riichi"`
	}

    raw.ActionType = RIICHI
    raw.TileToRiichi = obj.TileToRiichi

    return json.Marshal(raw)
}

func (Toss) Data() {}
func (obj Toss) MarshalJSON() ([]byte, error) {
    var raw struct {
		ActionType ActionType `json:"action_type"`
        TileToToss Tile `json:"tile_to_toss"`
	}

    raw.ActionType = TOSS
    raw.TileToToss = obj.TileToToss

    return json.Marshal(raw)
}

func (Skip) Data() {}
func (obj Skip) MarshalJSON() ([]byte, error) {
    var raw struct {
		ActionType ActionType `json:"action_type"`
        ActionToSkip Action `json:"action_to_skip"`
	}

    raw.ActionType = SKIP
    raw.ActionToSkip = obj.ActionToSkip

    return json.Marshal(raw)
}

func (obj *Skip) UnmarshalJSON(rawData []byte) error {
    var raw struct {
        ActionType ActionType `json:"action_type"`
        ActionToSkip ActionUnpacker `json:"action_to_skip"`
	}

	err := json.Unmarshal(rawData, &raw)
    obj.ActionToSkip = raw.ActionToSkip.Action

    return err
}

func (Pon) Data() {}
func (obj Pon) MarshalJSON() ([]byte, error) {
    var raw struct {
		ActionType ActionType `json:"action_type"`
        TileToPon Tile `json:"tile_to_pon"`
	}

    raw.ActionType = PON
    raw.TileToPon = obj.TileToPon

    return json.Marshal(raw)
}

func (Kan) Data() {}
func (obj Kan) MarshalJSON() ([]byte, error) {
    var raw struct {
		ActionType ActionType `json:"action_type"`
        TileToKan Tile `json:"tile_to_kan"`
	}

    raw.ActionType = KAN
    raw.TileToKan = obj.TileToKan

    return json.Marshal(raw)
}

func (Chii) Data() {}
func (obj Chii) MarshalJSON() ([]byte, error) {
    var raw struct {
		ActionType ActionType `json:"action_type"`
        TileToChii Tile `json:"tile_to_chii"`
        TilesInHand [2]Tile `json:"tiles_in_hand"`
	}

    raw.ActionType = CHII
    raw.TileToChii = obj.TileToChii
    raw.TilesInHand = obj.TilesInHand

    return json.Marshal(raw)
}

func (Draw) Data() {}
func (obj Draw) MarshalJSON() ([]byte, error) {
    var raw struct {
		ActionType ActionType `json:"action_type"`
        DrawnTile Tile `json:"drawn_tile"`
	}

    raw.ActionType = DRAW
    raw.DrawnTile = obj.DrawnTile

    return json.Marshal(raw)
}


func (msg *ActionUnpacker) Uncover() Action {
	return msg.Action
}

func (msg *ActionUnpacker) UnmarshalJSON(rawData []byte) error {
	var raw struct {
		ActionType ActionType `json:"action_type"`
	}

	if err := json.Unmarshal(rawData, &raw); err != nil {
		return err
	}

	switch raw.ActionType {
	case RON:
		message := Ron{}
		err := json.Unmarshal(rawData, &message)
		if err != nil {
			return err
		}
		msg.Action = message
	case TSUMO:
		message := Tsumo{}
		err := json.Unmarshal(rawData, &message)
		if err != nil {
			return err
		}
		msg.Action = message
	case RIICHI:
		message := Riichi{}
		err := json.Unmarshal(rawData, &message)
		if err != nil {
			return err
		}
		msg.Action = message
	case TOSS:
		message := Toss{}
		err := json.Unmarshal(rawData, &message)
		if err != nil {
			return err
		}
		msg.Action = message
	case SKIP:
		message := Skip{}
		err := json.Unmarshal(rawData, &message)
		if err != nil {
			return err
		}
		msg.Action = message
	case PON:
		message := Pon{}
		err := json.Unmarshal(rawData, &message)
		if err != nil {
			return err
		}
		msg.Action = message
	case KAN:
		message := Kan{}
		err := json.Unmarshal(rawData, &message)
		if err != nil {
			return err
		}
		msg.Action = message
	case CHII:
		message := Chii{}
		err := json.Unmarshal(rawData, &message)
		if err != nil {
			return err
		}
		msg.Action = message
	case DRAW:
		message := Draw{}
		err := json.Unmarshal(rawData, &message)
		if err != nil {
			return err
		}
		msg.Action = message
	default:
		return fmt.Errorf("unexpected type: %#v", raw.ActionType)
	}
	return nil
}

type ActionHandler[T any, E any] interface {
    HandleRon(Ron, E) (T, error)
    HandleTsumo(Tsumo, E) (T, error)
    HandleRiichi(Riichi, E) (T, error)
    HandleToss(Toss, E) (T, error)
    HandleSkip(Skip, E) (T, error)
    HandlePon(Pon, E) (T, error)
    HandleKan(Kan, E) (T, error)
    HandleChii(Chii, E) (T, error)
    HandleDraw(Draw, E) (T, error)
}

func ActionDecode[T any, E any](handler ActionHandler[T, E], data Action, extraData E) (ret T, err error) {
	switch v := data.(type) {
    case Ron:
        return handler.HandleRon(v, extraData)
    case Tsumo:
        return handler.HandleTsumo(v, extraData)
    case Riichi:
        return handler.HandleRiichi(v, extraData)
    case Toss:
        return handler.HandleToss(v, extraData)
    case Skip:
        return handler.HandleSkip(v, extraData)
    case Pon:
        return handler.HandlePon(v, extraData)
    case Kan:
        return handler.HandleKan(v, extraData)
    case Chii:
        return handler.HandleChii(v, extraData)
    case Draw:
        return handler.HandleDraw(v, extraData)
	default:
		return ret, fmt.Errorf("unexpected type: %#v", data)
	}
}
