// Code generated by "stringer -type=ActionType"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RON-0]
	_ = x[TSUMO-1]
	_ = x[RIICHI-2]
	_ = x[TOSS-3]
	_ = x[SKIP-4]
	_ = x[PON-5]
	_ = x[KAN-6]
	_ = x[CHII-7]
	_ = x[DRAW-8]
}

const _ActionType_name = "RONTSUMORIICHITOSSSKIPPONKANCHIIDRAW"

var _ActionType_index = [...]uint8{0, 3, 8, 14, 18, 22, 25, 28, 32, 36}

func (i ActionType) String() string {
	if i >= ActionType(len(_ActionType_index)-1) {
		return "ActionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ActionType_name[_ActionType_index[i]:_ActionType_index[i+1]]
}
