//go:build ignore
// +build ignore

package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"log"
	"os"
	"reflect"
	"strings"
	"text/template"
)

type Names []string
type Tags []string

type FieldDecl struct {
	Name string
	Type string
	Tag  string
}

type StructDecl struct {
	Name   string
	Fields []FieldDecl
}

type StructDecls []StructDecl

func parseStruct(structType *ast.StructType, fset *token.FileSet) (decls []FieldDecl) {
	for _, field := range structType.Fields.List {
		if len(field.Names) != 1 {
			panic("Unexpected")
		}

		var buf bytes.Buffer
		printer.Fprint(&buf, fset, field.Type)
		fmt.Println("Field type:", buf.String())

		decls = append(decls, FieldDecl{
			Name: field.Names[0].Name,
			Type: buf.String(),
			Tag:  field.Tag.Value,
		})
	}
	return decls
}

func main() {
	fset := token.NewFileSet()
	files := []string{"action.go"}

	typeIdentName := os.Args[1]
	fmt.Println(typeIdentName)

	// Collect type names
	var interfaceName string
	var interfaceImplementor string
	structDecls := make([]StructDecl, 0)

	for _, fname := range files {
		f, err := parser.ParseFile(fset, fname, nil, 0)
		if err != nil {
			log.Fatal(err)
		}

		for _, decl := range f.Decls {
			// A generic declaration that is a type
			if gd, ok := decl.(*ast.GenDecl); ok && gd.Tok.String() == "type" {
				// List of items under a type block (there can be more than one)
				for _, spec := range gd.Specs {
					typeSpec := spec.(*ast.TypeSpec)
					fmt.Println("Type: ", reflect.TypeOf(typeSpec.Type))

					switch v := typeSpec.Type.(type) {
					case *ast.ArrayType:
					case *ast.BadExpr:
					case *ast.BasicLit:
					case *ast.BinaryExpr:
					case *ast.CallExpr:
					case *ast.ChanType:
					case *ast.CompositeLit:
					case *ast.Ellipsis:
					case *ast.FuncLit:
					case *ast.FuncType:
					case *ast.Ident:
						// fmt.Println("Ident: ", v.Name)
						// typeIndicator.Name = typeSpec.Name.Name
						// typeIndicator.UnderlyingType = v
					case *ast.IndexExpr:
					case *ast.IndexListExpr:
					case *ast.InterfaceType:
						fmt.Println("Interface:", typeSpec.Name.Name)
						interfaceName = typeSpec.Name.Name
						for _, method := range v.Methods.List {
							interfaceImplementor = method.Names[0].Name
						}

					case *ast.KeyValueExpr:
					case *ast.MapType:
					case *ast.ParenExpr:
					case *ast.SelectorExpr:
					case *ast.SliceExpr:
					case *ast.StarExpr:
						break

					case *ast.StructType:
						decls := parseStruct(v, fset)
						structDecls = append(structDecls, StructDecl{
							Name:   typeSpec.Name.Name,
							Fields: decls,
						})

					case *ast.TypeAssertExpr:
					case *ast.UnaryExpr:
						fmt.Println("something else")
					default:
						panic(fmt.Sprintf("unexpected ast.Expr: %#v", typeSpec.Type))
					}
				}
			}
		}
		fmt.Println("list: ", structDecls)

	}

	// Generate the registry file
	tmpl := template.Must(template.New("action").Funcs(template.FuncMap{
		"upper": strings.ToUpper,
		"lower": strings.ToLower,
	}).Parse(registryTemplate))
	out, err := os.Create("action_generated.go")
	if err != nil {
		log.Fatal(err)
	}
	defer out.Close()

	err = tmpl.Execute(out, struct {
		InterfaceName string
		InterfaceImpl string
		Decls         StructDecls
	}{
		interfaceName,
		interfaceImplementor,
		structDecls,
	})

	if err != nil {
		fmt.Println(err)
	}
}

const registryTemplate = `// Code generated by go generate; DO NOT EDIT.
package core

import (
    "encoding/json"
    "fmt"
)

type {{.InterfaceName}}Type uint8

type {{.InterfaceName}}Unpacker struct {
    {{.InterfaceName}}
}

const (
{{- range .Decls }}
	{{upper .Name }} {{$.InterfaceName}}Type = iota
{{- end }}
)

{{- range .Decls }}
func ({{ .Name }}) {{ $.InterfaceImpl }}() {}
func (obj {{ .Name}}) MarshalJSON() ([]byte, error) {
    var raw struct {
		{{$.InterfaceName}}Type {{$.InterfaceName}}Type ` + "`" + `json:"{{lower $.InterfaceName}}_type"` + "`" + `
		{{- range .Fields}}
        {{.Name}} {{.Type}} {{.Tag}}
		{{- end}}
	}

    raw.{{$.InterfaceName}}Type = {{upper .Name}}
	{{- range .Fields}}
    raw.{{.Name}} = obj.{{.Name}}
	{{- end}}

    return json.Marshal(raw)
}
{{- end }}

func (msg *{{.InterfaceName}}Unpacker) Uncover() {{.InterfaceName}} {
	return msg.{{.InterfaceName}}
}

func (msg *{{.InterfaceName}}Unpacker) UnmarshalJSON(rawData []byte) error {
	var raw struct {
		{{$.InterfaceName}}Type {{$.InterfaceName}}Type ` + "`" + `json:"{{lower $.InterfaceName}}_type"` + "`" + `
	}

	if err := json.Unmarshal(rawData, &raw); err != nil {
		return err
	}

	switch raw.{{$.InterfaceName}}Type {
{{- range .Decls }}
	case {{upper .Name}}:
		message := {{.Name}}{}
		err := json.Unmarshal(rawData, &message)
		if err != nil {
			return err
		}
		msg.{{$.InterfaceName}} = message
{{- end }}
	default:
		return fmt.Errorf("unexpected type: %#v", raw.{{$.InterfaceName}}Type)
	}
	return nil
}

type {{ .InterfaceName -}}Handler[T any, E any] interface {
{{- range .Decls}}
    Handle{{.Name}}({{.Name}}, E) (T, error)
{{- end }}
}

func {{.InterfaceName}}Decode[T any, E any](handler {{.InterfaceName}}Handler[T, E], data {{.InterfaceName}}, extraData E) (ret T, err error) {
	switch v := data.(type) {
{{- range .Decls}}
    case {{.Name}}:
        return handler.Handle{{.Name}}(v, extraData)
{{- end }}
	default:
		return ret, fmt.Errorf("unexpected type: %#v", data)
	}
}
`
