//go:build ignore
// +build ignore

package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"log"
	"os"
	"reflect"
	"text/template"
)

type Names []string
type Tags []string

func parseStruct(structType *ast.StructType) (names Names, tags Tags) {
	for _, field := range structType.Fields.List {
		if len(field.Names) != 1 {
			panic("Unexpected")
		}

		names = append(names, field.Names[0].Name)
		tags = append(tags, field.Tag.Value)
	}
	return names, tags
}

func main() {
	fset := token.NewFileSet()
	files := []string{"action.go"}

	typeIdentName := os.Args[1]

	// Collect type names
	var types []string
	for _, fname := range files {
		f, err := parser.ParseFile(fset, fname, nil, 0)
		if err != nil {
			log.Fatal(err)
		}

		for _, decl := range f.Decls {
			// A generic declaration that is a type
			if gd, ok := decl.(*ast.GenDecl); ok && gd.Tok.String() == "type" {
				// List of items under a type block (there can be more than one)
				for _, spec := range gd.Specs {
					typeSpec := spec.(*ast.TypeSpec)
					types = append(types, typeSpec.Name.Name)
					fmt.Println("Type: ", reflect.TypeOf(typeSpec.Type))

					switch v := typeSpec.Type.(type) {
					case *ast.ArrayType:
					case *ast.BadExpr:
					case *ast.BasicLit:
					case *ast.BinaryExpr:
					case *ast.CallExpr:
					case *ast.ChanType:
					case *ast.CompositeLit:
					case *ast.Ellipsis:
					case *ast.FuncLit:
					case *ast.FuncType:
					case *ast.Ident:
						// fmt.Println("Ident: ", v.Name)
						// typeIndicator.Name = typeSpec.Name.Name
						// typeIndicator.UnderlyingType = v
					case *ast.IndexExpr:
					case *ast.IndexListExpr:
					case *ast.InterfaceType:
					case *ast.KeyValueExpr:
					case *ast.MapType:
					case *ast.ParenExpr:
					case *ast.SelectorExpr:
					case *ast.SliceExpr:
					case *ast.StarExpr:
						break
					case *ast.StructType:
						names, fields := parseStruct(v)
						fmt.Println(names, fields)
					case *ast.TypeAssertExpr:
					case *ast.UnaryExpr:
						fmt.Println("something else")
					default:
						panic(fmt.Sprintf("unexpected ast.Expr: %#v", typeSpec.Type))
					}

					fmt.Println()
				}
			}
		}
	}

	// Generate the registry file
	tmpl := template.Must(template.New("action").Parse(registryTemplate))
	out, err := os.Create("action_generated.go")
	if err != nil {
		log.Fatal(err)
	}
	defer out.Close()

	tmpl.Execute(out, types)
}

const registryTemplate = `// Code generated by go generate; DO NOT EDIT.
package core

var typeRegistry = map[string]func() interface{}{
{{- range . }}
    "{{ . }}": func() interface{} { return new({{ . }}) },
{{- end }}
}
`
