// Code generated by "stringer -type=Tile"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Manzu-0]
	_ = x[Pinzu-16]
	_ = x[Souzu-32]
	_ = x[Kazehai-48]
	_ = x[EastTile-48]
	_ = x[SouthTile-49]
	_ = x[WestTile-50]
	_ = x[NorthTile-51]
	_ = x[Sangenpai-52]
	_ = x[White-52]
	_ = x[Red-53]
	_ = x[Green-54]
	_ = x[DoraTile-64]
	_ = x[RedTile-128]
	_ = x[Hidden-254]
	_ = x[Invalid-255]
	_ = x[TileMask-48]
}

const (
	_Tile_name_0 = "Manzu"
	_Tile_name_1 = "Pinzu"
	_Tile_name_2 = "Souzu"
	_Tile_name_3 = "KazehaiSouthTileWestTileNorthTileSangenpaiRedGreen"
	_Tile_name_4 = "DoraTile"
	_Tile_name_5 = "RedTile"
	_Tile_name_6 = "HiddenInvalid"
)

var (
	_Tile_index_3 = [...]uint8{0, 7, 16, 24, 33, 42, 45, 50}
	_Tile_index_6 = [...]uint8{0, 6, 13}
)

func (i Tile) String() string {
	switch {
	case i == 0:
		return _Tile_name_0
	case i == 16:
		return _Tile_name_1
	case i == 32:
		return _Tile_name_2
	case 48 <= i && i <= 54:
		i -= 48
		return _Tile_name_3[_Tile_index_3[i]:_Tile_index_3[i+1]]
	case i == 64:
		return _Tile_name_4
	case i == 128:
		return _Tile_name_5
	case 254 <= i && i <= 255:
		i -= 254
		return _Tile_name_6[_Tile_index_6[i]:_Tile_index_6[i+1]]
	default:
		return "Tile(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
