* 2025-12-03
- FSM methods should avoid storing, checking, and modifying their own data
  - Storing just the state is fine. Rely on other things to check correctness for you
  - Creates a lot of dependencies in case the data that they need is outside of what they have
  - i.e. compose the state machine in other functions
  - Also hard to reason about correctness
- OTOH, storing state in the FSM means that we don't have to dig through a ton of dereferences to get to the data that we want
- Either we define functions that operate on both the state or the data, or have the state store the data and update the data based on the state
- Going with the second approach, storing the data in the state, but as fields of the state machine so that we don't die from dereferencing everything
- Should combine state and data (for both round and game), so that it's easier to pass data around

* 2025-12-04
- Clean up arena, calling more fine grained hooks into game
- Move game state into game and set up one object

* 2025-12-08
- Perform testing success of actions into its own file
- Pull in required data when needed, no receiver
- Also check for tsumo when drawing tile
- Readd discard tile logic
- Need to try running the game now

* 2025-12-09
- Fixed up some issues with ordering
- Implement ECS

* 2025-12-13
- I think I should do some rethinking of the architecture.
- Instead of storing state explicitly in the FSM, I should encode the state of the program in the control flow of the server
    - What this means: Use a coroutine that yields control back when it needs to wait for input or perform an action.
- On the client side, we can use async/await to handle responses in a linear fashion, but we also need to handle events from the server
- Every request should have a response indicating its success
- Can have generic responses, and also specific responses to data
- Events should be the only ones that can modify the internal state of the client
** Client
- Client should use event bus architecture, since what is happening should be driven by the server
- Server sends out global updates
- Where does request info come in?
    - We should have another message class: request info
    - Request various amounts of information like board state

* 2025-12-14
- Going back on the ECS idea. It's not needed for this type of project
- We should use promises/async to handle state
  - use promise race to handle multiple async sources
    - user events (mouse, ui)
    - server events
  - async await the promises
