// Code generated by go generate; DO NOT EDIT.

// Action Union Type and Enum
import {Tile} from "../game/tile";

export type Action = Ron | Tsumo | Riichi | Toss | Skip | Pon | Kan | Chii | Draw;

export enum ActionType {
    Ron = 0,
    Tsumo = 1,
    Riichi = 2,
    Toss = 3,
    Skip = 4,
    Pon = 5,
    Kan = 6,
    Chii = 7,
    Draw = 8,
}

// Individual struct interfaces

class WinResult {
}

export interface Ron {
    tile_to_ron: Tile;
    win_result: WinResult;
}

export interface Tsumo {
    tile_to_tsumo: Tile;
}

export interface Riichi {
    tile_to_riichi: Tile;
}

export interface Toss {
    tile_to_toss: Tile;
}

export interface Skip {
    action_to_skip: Action;
}

export interface Pon {
    tile_to_pon: Tile;
}

export interface Kan {
    tile_to_kan: Tile;
}

export interface Chii {
    tile_to_chii: Tile;
    tiles_in_hand: Tile[];
}

export interface Draw {
    drawn_tile: Tile;
}
