// Code generated by go generate; DO NOT EDIT.

// Action Union Type and Enum
import { Tile } from "./tile";
import { Action } from "./action_generated";

export type Action = Ron | Tsumo | Riichi | Toss | Skip | Pon | Kan | Chii | Draw;

export enum ActionType {
    Ron = 0,
    Tsumo = 1,
    Riichi = 2,
    Toss = 3,
    Skip = 4,
    Pon = 5,
    Kan = 6,
    Chii = 7,
    Draw = 8,
}

// Individual struct interfaces

class WinResult {

}

export interface Ron {
    action_type: ActionType.Ron;
    tile_to_ron: Tile;
    win_result: WinResult;
}

export interface Tsumo {
    action_type: ActionType.Tsumo;
    tile_to_tsumo: Tile;
}

export interface Riichi {
    action_type: ActionType.Riichi;
    tile_to_riichi: Tile;
}

export interface Toss {
    action_type: ActionType.Toss;
    tile_to_toss: Tile;
}

export interface Skip {
    action_type: ActionType.Skip;
    action_to_skip: Action;
}

export interface Pon {
    action_type: ActionType.Pon;
    tile_to_pon: Tile;
}

export interface Kan {
    action_type: ActionType.Kan;
    tile_to_kan: Tile;
}

export interface Chii {
    action_type: ActionType.Chii;
    tile_to_chii: Tile;
    tiles_in_hand: Tile[];
}

export interface Draw {
    action_type: ActionType.Draw;
    drawn_tile: Tile;
}
