// Code generated by go generate; DO NOT EDIT.

// ArenaEvent Union Type and Enum
import {BoardEvent} from "./board_event";

export type ArenaEventMessage =  ArenaEvent & {
    arenaevent_type: ArenaEventType;
}

export type ArenaEvent = PlayerJoinedEvent | PlayerQuitEvent | GameStartedEvent | ArenaBoardEvent;

export enum ArenaEventType {
    PlayerJoinedEvent = 0,
    PlayerQuitEvent = 1,
    GameStartedEvent = 2,
    ArenaBoardEvent = 3,
}

// Individual struct interfaces

export interface PlayerJoinedEvent {
    name: string;
    id: string;
}

export interface PlayerQuitEvent {
    name: string;
}

export interface GameStartedEvent {
}

export interface ArenaBoardEvent {
    board_event: BoardEvent;
}
