// Code generated by go generate; DO NOT EDIT.

// ArenaAction Union Type and Enum
import {Action} from "./action_generated";

export type ArenaAction = StartGameActionData | PlayerQuitActionData | PlayerActionData;

export enum ArenaActionType {
    StartGameActionData = 0,
    PlayerQuitActionData = 1,
    PlayerActionData = 2,
}

// Individual struct interfaces

export interface StartGameActionData {
    arenaaction_type: ArenaActionType.StartGameActionData;
}

export interface PlayerQuitActionData {
    arenaaction_type: ArenaActionType.PlayerQuitActionData;
}

export interface PlayerActionData {
    arenaaction_type: ArenaActionType.PlayerActionData;
    action: Action;
}
