// Code generated by go generate; DO NOT EDIT.

// ArenaEvent Union Type and Enum
import {BoardEvent} from "./board_event_generated";
import {AgentInfo} from "../game/agent_info";

export type ArenaEvent = PlayerJoinedEvent | PlayerQuitEvent | GameStartedEvent | ArenaBoardEvent;

export enum ArenaEventType {
    PlayerJoinedEvent = 0,
    PlayerQuitEvent = 1,
    GameStartedEvent = 2,
    ArenaBoardEvent = 3,
}

// Individual struct interfaces

export interface PlayerJoinedEvent {
    arenaevent_type: ArenaEventType.PlayerJoinedEvent;
    agent_info: AgentInfo;
}

export interface PlayerQuitEvent {
    arenaevent_type: ArenaEventType.PlayerQuitEvent;
    name: string;
}

export interface GameStartedEvent {
    arenaevent_type: ArenaEventType.GameStartedEvent;
}

export interface ArenaBoardEvent {
    arenaevent_type: ArenaEventType.ArenaBoardEvent;
    board_event: BoardEvent;
}
