// Code generated by go generate; DO NOT EDIT.

// BoardEvent Union Type and Enum
import { Action } from './action_generated'
import { Setup } from '../game/setup'

export type BoardEvent =
  | PlayerActionEvent
  | PotentialActionEvent
  | GameSetupEvent
  | GameEndEvent

export enum BoardEventType {
  PlayerActionEvent = 0,
  PotentialActionEvent = 1,
  GameSetupEvent = 2,
  GameEndEvent = 3,
}

// Individual struct interfaces

class GameResult {}

export interface PlayerActionEvent {
  boardevent_type: BoardEventType.PlayerActionEvent
  action_data: Action
  from_player: number
}

export interface PotentialActionEvent {
  boardevent_type: BoardEventType.PotentialActionEvent
  actions: Action[]
}

export interface GameSetupEvent {
  boardevent_type: BoardEventType.GameSetupEvent
  setup: Setup[]
}

export interface GameEndEvent {
  boardevent_type: BoardEventType.GameEndEvent
  result: GameResult
}
