// Code generated by go generate; DO NOT EDIT.

// BoardEvent Union Type and Enum
import {Action} from "./action_generated";
import {Setup} from "../types/setup";

export type BoardEvent = PlayerActionEvent | PotentialActionEvent | NoNakiEvent | GameSetupEvent | RoundEndEvent | GameEndEvent;

export enum BoardEventType {
    PlayerActionEvent = 0,
    PotentialActionEvent = 1,
    NoNakiEvent = 2,
    GameSetupEvent = 3,
    RoundEndEvent = 4,
    GameEndEvent = 5,
}

// Individual struct interfaces

class GameResult {

}

export interface PlayerActionEvent {
    boardevent_type: BoardEventType.PlayerActionEvent;
    action_data: Action;
    from_player: number;
}

export interface PotentialActionEvent {
    boardevent_type: BoardEventType.PotentialActionEvent;
    actions: Action[];
}

export interface NoNakiEvent {
    boardevent_type: BoardEventType.NoNakiEvent;
}

export interface GameSetupEvent {
    boardevent_type: BoardEventType.GameSetupEvent;
    setup: Setup[];
}

export interface RoundEndEvent {
    boardevent_type: BoardEventType.RoundEndEvent;
    round_result: RoundResult;
}

export interface GameEndEvent {
    boardevent_type: BoardEventType.GameEndEvent;
    result: GameResult;
}
