// Code generated by go generate; DO NOT EDIT.

// BoardEvent Union Type and Enum
import {Action} from "../game/action";

export type BoardEventMessage =  BoardEvent & {
    boardevent_type: BoardEventType;
}

export type BoardEvent = PlayerActionEvent | PotentialActionEvent | GameSetupEvent | GameEndEvent;

export enum BoardEventType {
    PlayerActionEvent = 0,
    PotentialActionEvent = 1,
    GameSetupEvent = 2,
    GameEndEvent = 3,
}

// Individual struct interfaces

export interface PlayerActionEvent {
    action_data: Action;
    from_player: number;
}

export interface PotentialActionEvent {
    action_data: Action;
}

class Setup {
}

export interface GameSetupEvent {
    setup: Setup[];
}

class GameResult {
}

export interface GameEndEvent {
    result: GameResult;
}
