// Code generated by go generate; DO NOT EDIT.

// ServerAction Union Type and Enum
import {ArenaAction} from "./arena_action_generated";

export type ServerAction = InitialMessageAction | JoinArenaAction | ServerArenaAction | ListArenasAction | CreateArenaAction | ArenaInfoAction | AddAIArenaAction | RemoveAIArenaAction;

export enum ServerActionType {
    InitialMessageAction = 0,
    JoinArenaAction = 1,
    ServerArenaAction = 2,
    ListArenasAction = 3,
    CreateArenaAction = 4,
    ArenaInfoAction = 5,
    AddAIArenaAction = 6,
    RemoveAIArenaAction = 7,
}

// Individual struct interfaces

export interface InitialMessageAction {
    serveraction_type: ServerActionType.InitialMessageAction;
    name: string;
}

export interface JoinArenaAction {
    serveraction_type: ServerActionType.JoinArenaAction;
    arena_name: string;
}

export interface ServerArenaAction {
    serveraction_type: ServerActionType.ServerArenaAction;
    arena_action: ArenaAction;
}

export interface ListArenasAction {
    serveraction_type: ServerActionType.ListArenasAction;
}

export interface CreateArenaAction {
    serveraction_type: ServerActionType.CreateArenaAction;
    arena_name: string;
}

export interface ArenaInfoAction {
    serveraction_type: ServerActionType.ArenaInfoAction;
}

export interface AddAIArenaAction {
    serveraction_type: ServerActionType.AddAIArenaAction;
}

export interface RemoveAIArenaAction {
    serveraction_type: ServerActionType.RemoveAIArenaAction;
}
