// Code generated by go generate; DO NOT EDIT.

// ServerResponse Union Type and Enum

import {AgentInfo} from "../game/agent_info";

export type ServerResponse = GenericResponse | ListArenasResponse | ArenaInfoResponse | GameInfoResponse;

export enum ServerResponseType {
    GenericResponse = 0,
    ListArenasResponse = 1,
    ArenaInfoResponse = 2,
    GameInfoResponse = 3,
}

// Individual struct interfaces

export interface GenericResponse {
    serverresponse_type: ServerResponseType.GenericResponse;
    success: boolean;
    fail_reason: string;
}

export interface ListArenasResponse {
    serverresponse_type: ServerResponseType.ListArenasResponse;
    success: boolean;
    arena_list: string[];
}

export interface ArenaInfoResponse {
    serverresponse_type: ServerResponseType.ArenaInfoResponse;
    success: boolean;
    name: string;
    agents: AgentInfo[];
    game_started: boolean;
    date_created: string;
}

export interface GameInfoResponse {
    serverresponse_type: ServerResponseType.GameInfoResponse;
}
