// Code generated by go generate; DO NOT EDIT.

// ServerEvent Union Type and Enum
import {ArenaEvent} from "./arena_event_generated";

export type ServerEventMessage =  ServerEvent & {
    serverevent_type: ServerEventType;
}

export type ServerEvent = ServerArenaEvent;

export enum ServerEventType {
    ServerArenaEvent = 0,
}

// Individual struct interfaces

export interface ServerArenaEvent {
    arena_message: ArenaEvent;
}
