// Code generated by "stringer -type=YakuType"; DO NOT EDIT.

package yaku

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NO_YAKU-1]
	_ = x[MENZEN_TSUMO_YAKU-2]
	_ = x[RIICHI_YAKU-4]
	_ = x[IPPATSU_YAKU-8]
	_ = x[PINFU_YAKU-16]
	_ = x[IIPEIKOU_YAKU-32]
	_ = x[HAITEI_YAOYUE_YAKU-64]
	_ = x[HOUTEI_RAOYUI_YAKU-128]
	_ = x[RINSHAN_KAIHOU_YAKU-256]
	_ = x[CHANKAN_YAKU-512]
	_ = x[TANYAO_YAKU-1024]
	_ = x[YAKUHAI_YAKU-2048]
	_ = x[DOUBLE_RIICHI_YAKU-4096]
	_ = x[CHANTAIYAO_YAKU-8192]
	_ = x[SANSHOKU_DOUJUN_YAKU-16384]
	_ = x[ITTSU_YAKU-32768]
	_ = x[TOITOI_YAKU-65536]
	_ = x[SANANKOU_YAKU-131072]
	_ = x[SANSHOKU_DOUKOU_YAKU-262144]
	_ = x[SANKANTSU_YAKU-524288]
	_ = x[CHIITOITSU_YAKU-1048576]
	_ = x[HONROUTOU_YAKU-2097152]
	_ = x[SHOUSANGEN_YAKU-4194304]
	_ = x[HONITSU_YAKU-8388608]
	_ = x[JUNCHAN_YAKU-16777216]
	_ = x[RYANPEIKOU_YAKU-33554432]
	_ = x[CHINITSU_YAKU-67108864]
	_ = x[KAZOE_YAKUMAN_YAKU-134217728]
	_ = x[KOKUSHI_MUSOU_YAKU-268435456]
	_ = x[KOKUSHI_MUSOU_THIRTEEN_WAITS_YAKU-536870912]
	_ = x[SUUANKOU_YAKU-1073741824]
	_ = x[DAISANGEN_YAKU-2147483648]
	_ = x[SHOUSUUSHII_YAKU-4294967296]
	_ = x[DAISUUSHII_YAKU-8589934592]
	_ = x[TSUUIISOU_YAKU-17179869184]
	_ = x[CHINROUTOU_YAKU-34359738368]
	_ = x[RYUUIISOU_YAKU-68719476736]
	_ = x[CHUUREN_POUTOU_YAKU-137438953472]
	_ = x[SUUKANTSU_YAKU-274877906944]
	_ = x[TENHOU_YAKU-549755813888]
	_ = x[CHIIHOU_YAKU-1099511627776]
	_ = x[NAGASHI_MANGAN_YAKU-2199023255552]
}

const _YakuType_name = "NO_YAKUMENZEN_TSUMO_YAKURIICHI_YAKUIPPATSU_YAKUPINFU_YAKUIIPEIKOU_YAKUHAITEI_YAOYUE_YAKUHOUTEI_RAOYUI_YAKURINSHAN_KAIHOU_YAKUCHANKAN_YAKUTANYAO_YAKUYAKUHAI_YAKUDOUBLE_RIICHI_YAKUCHANTAIYAO_YAKUSANSHOKU_DOUJUN_YAKUITTSU_YAKUTOITOI_YAKUSANANKOU_YAKUSANSHOKU_DOUKOU_YAKUSANKANTSU_YAKUCHIITOITSU_YAKUHONROUTOU_YAKUSHOUSANGEN_YAKUHONITSU_YAKUJUNCHAN_YAKURYANPEIKOU_YAKUCHINITSU_YAKUKAZOE_YAKUMAN_YAKUKOKUSHI_MUSOU_YAKUKOKUSHI_MUSOU_THIRTEEN_WAITS_YAKUSUUANKOU_YAKUDAISANGEN_YAKUSHOUSUUSHII_YAKUDAISUUSHII_YAKUTSUUIISOU_YAKUCHINROUTOU_YAKURYUUIISOU_YAKUCHUUREN_POUTOU_YAKUSUUKANTSU_YAKUTENHOU_YAKUCHIIHOU_YAKUNAGASHI_MANGAN_YAKU"

var _YakuType_map = map[YakuType]string{
	1:             _YakuType_name[0:7],
	2:             _YakuType_name[7:24],
	4:             _YakuType_name[24:35],
	8:             _YakuType_name[35:47],
	16:            _YakuType_name[47:57],
	32:            _YakuType_name[57:70],
	64:            _YakuType_name[70:88],
	128:           _YakuType_name[88:106],
	256:           _YakuType_name[106:125],
	512:           _YakuType_name[125:137],
	1024:          _YakuType_name[137:148],
	2048:          _YakuType_name[148:160],
	4096:          _YakuType_name[160:178],
	8192:          _YakuType_name[178:193],
	16384:         _YakuType_name[193:213],
	32768:         _YakuType_name[213:223],
	65536:         _YakuType_name[223:234],
	131072:        _YakuType_name[234:247],
	262144:        _YakuType_name[247:267],
	524288:        _YakuType_name[267:281],
	1048576:       _YakuType_name[281:296],
	2097152:       _YakuType_name[296:310],
	4194304:       _YakuType_name[310:325],
	8388608:       _YakuType_name[325:337],
	16777216:      _YakuType_name[337:349],
	33554432:      _YakuType_name[349:364],
	67108864:      _YakuType_name[364:377],
	134217728:     _YakuType_name[377:395],
	268435456:     _YakuType_name[395:413],
	536870912:     _YakuType_name[413:446],
	1073741824:    _YakuType_name[446:459],
	2147483648:    _YakuType_name[459:473],
	4294967296:    _YakuType_name[473:489],
	8589934592:    _YakuType_name[489:504],
	17179869184:   _YakuType_name[504:518],
	34359738368:   _YakuType_name[518:533],
	68719476736:   _YakuType_name[533:547],
	137438953472:  _YakuType_name[547:566],
	274877906944:  _YakuType_name[566:580],
	549755813888:  _YakuType_name[580:591],
	1099511627776: _YakuType_name[591:603],
	2199023255552: _YakuType_name[603:622],
}

func (i YakuType) String() string {
	if str, ok := _YakuType_map[i]; ok {
		return str
	}
	return "YakuType(" + strconv.FormatInt(int64(i), 10) + ")"
}
