// Code generated by go generate; DO NOT EDIT.
package core

import (
	"encoding/json"
	"fmt"
)

type ArenaEventType uint8

type ArenaEventUnpacker struct {
	ArenaEvent
}

const (
	PLAYERJOINEDEVENT ArenaEventType = iota
	PLAYERQUITEVENT   ArenaEventType = iota
	GAMESTARTEDEVENT  ArenaEventType = iota
	ARENABOARDEVENT   ArenaEventType = iota
)

func (PlayerJoinedEvent) ArenaEventImpl() {}
func (obj PlayerJoinedEvent) MarshalJSON() ([]byte, error) {
	var raw struct {
		ArenaEventType ArenaEventType `json:"arenaevent_type"`
		AgentInfo      AgentInfo      `json:"agent_info"`
	}

	raw.ArenaEventType = PLAYERJOINEDEVENT
	raw.AgentInfo = obj.AgentInfo

	return json.Marshal(raw)
}

func (PlayerQuitEvent) ArenaEventImpl() {}
func (obj PlayerQuitEvent) MarshalJSON() ([]byte, error) {
	var raw struct {
		ArenaEventType ArenaEventType `json:"arenaevent_type"`
		Name           string         `json:"name"`
	}

	raw.ArenaEventType = PLAYERQUITEVENT
	raw.Name = obj.Name

	return json.Marshal(raw)
}

func (GameStartedEvent) ArenaEventImpl() {}
func (obj GameStartedEvent) MarshalJSON() ([]byte, error) {
	var raw struct {
		ArenaEventType ArenaEventType `json:"arenaevent_type"`
	}

	raw.ArenaEventType = GAMESTARTEDEVENT

	return json.Marshal(raw)
}

func (ArenaBoardEvent) ArenaEventImpl() {}
func (obj ArenaBoardEvent) MarshalJSON() ([]byte, error) {
	var raw struct {
		ArenaEventType ArenaEventType `json:"arenaevent_type"`
		BoardEvent     BoardEvent     `json:"board_event"`
	}

	raw.ArenaEventType = ARENABOARDEVENT
	raw.BoardEvent = obj.BoardEvent

	return json.Marshal(raw)
}

func (obj *ArenaBoardEvent) UnmarshalJSON(rawData []byte) error {
	var raw struct {
		ArenaEventType ArenaEventType     `json:"arenaevent_type"`
		BoardEvent     BoardEventUnpacker `json:"board_event"`
	}

	err := json.Unmarshal(rawData, &raw)
	obj.BoardEvent = raw.BoardEvent.BoardEvent

	return err
}

func (msg *ArenaEventUnpacker) Uncover() ArenaEvent {
	return msg.ArenaEvent
}

func (msg *ArenaEventUnpacker) UnmarshalJSON(rawData []byte) error {
	var raw struct {
		ArenaEventType ArenaEventType `json:"arenaevent_type"`
	}

	if err := json.Unmarshal(rawData, &raw); err != nil {
		return err
	}

	switch raw.ArenaEventType {
	case PLAYERJOINEDEVENT:
		message := PlayerJoinedEvent{}
		err := json.Unmarshal(rawData, &message)
		if err != nil {
			return err
		}
		msg.ArenaEvent = message
	case PLAYERQUITEVENT:
		message := PlayerQuitEvent{}
		err := json.Unmarshal(rawData, &message)
		if err != nil {
			return err
		}
		msg.ArenaEvent = message
	case GAMESTARTEDEVENT:
		message := GameStartedEvent{}
		err := json.Unmarshal(rawData, &message)
		if err != nil {
			return err
		}
		msg.ArenaEvent = message
	case ARENABOARDEVENT:
		message := ArenaBoardEvent{}
		err := json.Unmarshal(rawData, &message)
		if err != nil {
			return err
		}
		msg.ArenaEvent = message
	default:
		return fmt.Errorf("unexpected type: %#v", raw.ArenaEventType)
	}
	return nil
}

type ArenaEventHandler[T any, E any] interface {
	HandlePlayerJoinedEvent(PlayerJoinedEvent, E) (T, error)
	HandlePlayerQuitEvent(PlayerQuitEvent, E) (T, error)
	HandleGameStartedEvent(GameStartedEvent, E) (T, error)
	HandleArenaBoardEvent(ArenaBoardEvent, E) (T, error)
}

func ArenaEventDecode[T any, E any](handler ArenaEventHandler[T, E], data ArenaEvent, extraData E) (ret T, err error) {
	switch v := data.(type) {
	case PlayerJoinedEvent:
		return handler.HandlePlayerJoinedEvent(v, extraData)
	case PlayerQuitEvent:
		return handler.HandlePlayerQuitEvent(v, extraData)
	case GameStartedEvent:
		return handler.HandleGameStartedEvent(v, extraData)
	case ArenaBoardEvent:
		return handler.HandleArenaBoardEvent(v, extraData)
	default:
		return ret, fmt.Errorf("unexpected type: %#v", data)
	}
}
