// Code generated by "stringer -type=ArenaEventType"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PLAYERJOINEDEVENT-0]
	_ = x[PLAYERQUITEVENT-1]
	_ = x[GAMESTARTEDEVENT-2]
	_ = x[ARENABOARDEVENT-3]
}

const _ArenaEventType_name = "PLAYERJOINEDEVENTPLAYERQUITEVENTGAMESTARTEDEVENTARENABOARDEVENT"

var _ArenaEventType_index = [...]uint8{0, 17, 32, 48, 63}

func (i ArenaEventType) String() string {
	if i >= ArenaEventType(len(_ArenaEventType_index)-1) {
		return "ArenaEventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ArenaEventType_name[_ArenaEventType_index[i]:_ArenaEventType_index[i+1]]
}
