// Code generated by "stringer -type=ArenaActionType"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[STARTGAMEACTIONDATA-0]
	_ = x[PLAYERQUITACTIONDATA-1]
	_ = x[PLAYERACTIONDATA-2]
}

const _ArenaActionType_name = "STARTGAMEACTIONDATAPLAYERQUITACTIONDATAPLAYERACTIONDATA"

var _ArenaActionType_index = [...]uint8{0, 19, 39, 55}

func (i ArenaActionType) String() string {
	if i >= ArenaActionType(len(_ArenaActionType_index)-1) {
		return "ArenaActionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ArenaActionType_name[_ArenaActionType_index[i]:_ArenaActionType_index[i+1]]
}
