// Code generated by go generate; DO NOT EDIT.
package core

import (
	"encoding/json"
	"fmt"
	. "codeberg.org/ijnakashiar/LibreRiichi/core/game_data"
)

type BoardEventType uint8

type BoardEventUnpacker struct {
	BoardEvent
}

const (
	PLAYERACTIONEVENTDATA BoardEventType = iota
	POTENTIALACTIONEVENTDATA BoardEventType = iota
	GAMESETUPEVENTDATA BoardEventType = iota
	GAMEENDEVENTDATA BoardEventType = iota
)
func (PlayerActionEventData) BoardEventWrapper() {}
func (obj PlayerActionEventData) MarshalJSON() ([]byte, error) {
	var raw struct {
		BoardEventType BoardEventType `json:"boardevent_type"`
		Action Action `json:"action_data"`
		FromPlayer uint8 `json:"from_player"`
	}

	raw.BoardEventType = PLAYERACTIONEVENTDATA
	raw.Action = obj.Action
	raw.FromPlayer = obj.FromPlayer

	return json.Marshal(raw)
}

func (obj PlayerActionEventData) UnmarshalJSON(rawData []byte) error {
    var raw struct {
        BoardEventType BoardEventType `json:"boardevent_type"`
        Action ActionUnpacker `json:"action_data"`
        FromPlayer uint8 `json:"from_player"`
	}

	err := json.Unmarshal(rawData, &raw)

    return err
}

func (PotentialActionEventData) BoardEventWrapper() {}
func (obj PotentialActionEventData) MarshalJSON() ([]byte, error) {
    var raw struct {
		BoardEventType BoardEventType `json:"boardevent_type"`
        Action Action `json:"action_data"`
	}

    raw.BoardEventType = POTENTIALACTIONEVENTDATA
    raw.Action = obj.Action

    return json.Marshal(raw)
}

func (obj PotentialActionEventData) UnmarshalJSON(rawData []byte) error {
    var raw struct {
        BoardEventType BoardEventType `json:"boardevent_type"`
        Action ActionUnpacker `json:"action_data"`
	}

	err := json.Unmarshal(rawData, &raw)

    return err
}

func (GameSetupEventData) BoardEventWrapper() {}
func (obj GameSetupEventData) MarshalJSON() ([]byte, error) {
    var raw struct {
		BoardEventType BoardEventType `json:"boardevent_type"`
        Setup []Setup `json:"setup"`
	}

    raw.BoardEventType = GAMESETUPEVENTDATA
    raw.Setup = obj.Setup

    return json.Marshal(raw)
}

func (GameEndEventData) BoardEventWrapper() {}
func (obj GameEndEventData) MarshalJSON() ([]byte, error) {
    var raw struct {
		BoardEventType BoardEventType `json:"boardevent_type"`
        GameResult GameResult `json:"result"`
	}

    raw.BoardEventType = GAMEENDEVENTDATA
    raw.GameResult = obj.GameResult

    return json.Marshal(raw)
}


func (msg *BoardEventUnpacker) Uncover() BoardEvent {
	return msg.BoardEvent
}

func (msg *BoardEventUnpacker) UnmarshalJSON(rawData []byte) error {
	var raw struct {
		BoardEventType BoardEventType `json:"boardevent_type"`
	}

	if err := json.Unmarshal(rawData, &raw); err != nil {
		return err
	}

	switch raw.BoardEventType {
	case PLAYERACTIONEVENTDATA:
		message := PlayerActionEventData{}
		err := json.Unmarshal(rawData, &message)
		if err != nil {
			return err
		}
		msg.BoardEvent = message
	case POTENTIALACTIONEVENTDATA:
		message := PotentialActionEventData{}
		err := json.Unmarshal(rawData, &message)
		if err != nil {
			return err
		}
		msg.BoardEvent = message
	case GAMESETUPEVENTDATA:
		message := GameSetupEventData{}
		err := json.Unmarshal(rawData, &message)
		if err != nil {
			return err
		}
		msg.BoardEvent = message
	case GAMEENDEVENTDATA:
		message := GameEndEventData{}
		err := json.Unmarshal(rawData, &message)
		if err != nil {
			return err
		}
		msg.BoardEvent = message
	default:
		return fmt.Errorf("unexpected type: %#v", raw.BoardEventType)
	}
	return nil
}

type BoardEventHandler[T any, E any] interface {
    HandlePlayerActionEventData(PlayerActionEventData, E) (T, error)
    HandlePotentialActionEventData(PotentialActionEventData, E) (T, error)
    HandleGameSetupEventData(GameSetupEventData, E) (T, error)
    HandleGameEndEventData(GameEndEventData, E) (T, error)
}

func BoardEventDecode[T any, E any](handler BoardEventHandler[T, E], data BoardEvent, extraData E) (ret T, err error) {
	switch v := data.(type) {
	case PlayerActionEventData:
		return handler.HandlePlayerActionEventData(v, extraData)
	case PotentialActionEventData:
		return handler.HandlePotentialActionEventData(v, extraData)
	case GameSetupEventData:
		return handler.HandleGameSetupEventData(v, extraData)
	case GameEndEventData:
		return handler.HandleGameEndEventData(v, extraData)
	default:
		return ret, fmt.Errorf("unexpected type: %#v", data)
	}
}
