// Code generated by go generate; DO NOT EDIT.
package core

import (
    "encoding/json"
    "fmt"
    . "codeberg.org/ijnakashiar/LibreRiichi/core/game_data"
)

type BoardEventType uint8

type BoardEventUnpacker struct {
    BoardEvent
}

const (
	PLAYERACTIONEVENT BoardEventType = iota
	POTENTIALACTIONEVENT BoardEventType = iota
	GAMESETUPEVENT BoardEventType = iota
	GAMEENDEVENT BoardEventType = iota
)
func (PlayerActionEvent) BoardEventWrapper() {}
func (obj PlayerActionEvent) MarshalJSON() ([]byte, error) {
    var raw struct {
		BoardEventType BoardEventType `json:"boardevent_type"`
        Action Action `json:"action_data"`
        FromPlayer uint8 `json:"from_player"`
	}

    raw.BoardEventType = PLAYERACTIONEVENT
    raw.Action = obj.Action
    raw.FromPlayer = obj.FromPlayer

    return json.Marshal(raw)
}

func (obj *PlayerActionEvent) UnmarshalJSON(rawData []byte) error {
    var raw struct {
        BoardEventType BoardEventType `json:"boardevent_type"`
        Action ActionUnpacker `json:"action_data"`
        FromPlayer uint8 `json:"from_player"`
	}

	err := json.Unmarshal(rawData, &raw)
    obj.Action = raw.Action.Action
    obj.FromPlayer = raw.FromPlayer

    return err
}

func (PotentialActionEvent) BoardEventWrapper() {}
func (obj PotentialActionEvent) MarshalJSON() ([]byte, error) {
    var raw struct {
		BoardEventType BoardEventType `json:"boardevent_type"`
        Action Action `json:"action_data"`
	}

    raw.BoardEventType = POTENTIALACTIONEVENT
    raw.Action = obj.Action

    return json.Marshal(raw)
}

func (obj *PotentialActionEvent) UnmarshalJSON(rawData []byte) error {
    var raw struct {
        BoardEventType BoardEventType `json:"boardevent_type"`
        Action ActionUnpacker `json:"action_data"`
	}

	err := json.Unmarshal(rawData, &raw)
    obj.Action = raw.Action.Action

    return err
}

func (GameSetupEvent) BoardEventWrapper() {}
func (obj GameSetupEvent) MarshalJSON() ([]byte, error) {
    var raw struct {
		BoardEventType BoardEventType `json:"boardevent_type"`
        Setup []Setup `json:"setup"`
	}

    raw.BoardEventType = GAMESETUPEVENT
    raw.Setup = obj.Setup

    return json.Marshal(raw)
}

func (GameEndEvent) BoardEventWrapper() {}
func (obj GameEndEvent) MarshalJSON() ([]byte, error) {
    var raw struct {
		BoardEventType BoardEventType `json:"boardevent_type"`
        GameResult GameResult `json:"result"`
	}

    raw.BoardEventType = GAMEENDEVENT
    raw.GameResult = obj.GameResult

    return json.Marshal(raw)
}


func (msg *BoardEventUnpacker) Uncover() BoardEvent {
	return msg.BoardEvent
}

func (msg *BoardEventUnpacker) UnmarshalJSON(rawData []byte) error {
	var raw struct {
		BoardEventType BoardEventType `json:"boardevent_type"`
	}

	if err := json.Unmarshal(rawData, &raw); err != nil {
		return err
	}

	switch raw.BoardEventType {
	case PLAYERACTIONEVENT:
		message := PlayerActionEvent{}
		err := json.Unmarshal(rawData, &message)
		if err != nil {
			return err
		}
		msg.BoardEvent = message
	case POTENTIALACTIONEVENT:
		message := PotentialActionEvent{}
		err := json.Unmarshal(rawData, &message)
		if err != nil {
			return err
		}
		msg.BoardEvent = message
	case GAMESETUPEVENT:
		message := GameSetupEvent{}
		err := json.Unmarshal(rawData, &message)
		if err != nil {
			return err
		}
		msg.BoardEvent = message
	case GAMEENDEVENT:
		message := GameEndEvent{}
		err := json.Unmarshal(rawData, &message)
		if err != nil {
			return err
		}
		msg.BoardEvent = message
	default:
		return fmt.Errorf("unexpected type: %#v", raw.BoardEventType)
	}
	return nil
}

type BoardEventHandler[T any, E any] interface {
    HandlePlayerActionEvent(PlayerActionEvent, E) (T, error)
    HandlePotentialActionEvent(PotentialActionEvent, E) (T, error)
    HandleGameSetupEvent(GameSetupEvent, E) (T, error)
    HandleGameEndEvent(GameEndEvent, E) (T, error)
}

func BoardEventDecode[T any, E any](handler BoardEventHandler[T, E], data BoardEvent, extraData E) (ret T, err error) {
	switch v := data.(type) {
    case PlayerActionEvent:
        return handler.HandlePlayerActionEvent(v, extraData)
    case PotentialActionEvent:
        return handler.HandlePotentialActionEvent(v, extraData)
    case GameSetupEvent:
        return handler.HandleGameSetupEvent(v, extraData)
    case GameEndEvent:
        return handler.HandleGameEndEvent(v, extraData)
	default:
		return ret, fmt.Errorf("unexpected type: %#v", data)
	}
}
