// Code generated by "stringer -type BoardEventType board_event_generated.go"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PLAYERACTIONEVENT-0]
	_ = x[POTENTIALACTIONEVENT-1]
	_ = x[NONAKIEVENT-2]
	_ = x[GAMESETUPEVENT-3]
	_ = x[ROUNDENDEVENT-4]
	_ = x[GAMEENDEVENT-5]
}

const _BoardEventType_name = "PLAYERACTIONEVENTPOTENTIALACTIONEVENTNONAKIEVENTGAMESETUPEVENTROUNDENDEVENTGAMEENDEVENT"

var _BoardEventType_index = [...]uint8{0, 17, 37, 48, 62, 75, 87}

func (i BoardEventType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_BoardEventType_index)-1 {
		return "BoardEventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BoardEventType_name[_BoardEventType_index[idx]:_BoardEventType_index[idx+1]]
}
