// Code generated by "stringer -type=BoardEventType"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PLAYERACTIONEVENT-0]
	_ = x[POTENTIALACTIONEVENT-1]
	_ = x[GAMESETUPEVENT-2]
	_ = x[GAMEENDEVENT-3]
}

const _BoardEventType_name = "PLAYERACTIONEVENTPOTENTIALACTIONEVENTGAMESETUPEVENTGAMEENDEVENT"

var _BoardEventType_index = [...]uint8{0, 17, 37, 51, 63}

func (i BoardEventType) String() string {
	if i >= BoardEventType(len(_BoardEventType_index)-1) {
		return "BoardEventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BoardEventType_name[_BoardEventType_index[i]:_BoardEventType_index[i+1]]
}
