// Code generated by "stringer -type MessageType messages/message.go"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RESPONSE-0]
	_ = x[REQUEST-1]
	_ = x[EVENT-2]
}

const _MessageType_name = "RESPONSEREQUESTEVENT"

var _MessageType_index = [...]uint8{0, 8, 15, 20}

func (i MessageType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_MessageType_index)-1 {
		return "MessageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MessageType_name[_MessageType_index[idx]:_MessageType_index[idx+1]]
}
