// Code generated by "stringer -type=ServerActionType"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[INITIALMESSAGEACTION-0]
	_ = x[JOINARENAACTION-1]
	_ = x[SERVERARENAACTION-2]
	_ = x[LISTARENASACTION-3]
	_ = x[CREATEARENAACTION-4]
	_ = x[ARENAINFOACTION-5]
}

const _ServerActionType_name = "INITIALMESSAGEACTIONJOINARENAACTIONSERVERARENAACTIONLISTARENASACTIONCREATEARENAACTIONARENAINFOACTION"

var _ServerActionType_index = [...]uint8{0, 20, 35, 52, 68, 85, 100}

func (i ServerActionType) String() string {
	if i >= ServerActionType(len(_ServerActionType_index)-1) {
		return "ServerActionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ServerActionType_name[_ServerActionType_index[i]:_ServerActionType_index[i+1]]
}
