// Code generated by "stringer -type=ServerResponseType"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GENERICRESPONSE-0]
	_ = x[LISTARENASRESPONSE-1]
	_ = x[ARENAINFORESPONSE-2]
}

const _ServerResponseType_name = "GENERICRESPONSELISTARENASRESPONSEARENAINFORESPONSE"

var _ServerResponseType_index = [...]uint8{0, 15, 33, 50}

func (i ServerResponseType) String() string {
	if i >= ServerResponseType(len(_ServerResponseType_index)-1) {
		return "ServerResponseType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ServerResponseType_name[_ServerResponseType_index[i]:_ServerResponseType_index[i+1]]
}
