// Code generated by go generate; DO NOT EDIT.
package core

import (
    "encoding/json"
    "fmt"
)

type ServerEventType uint8

type ServerEventUnpacker struct {
    ServerEvent
}

const (
	SERVERARENAEVENT ServerEventType = iota
)
func (ServerArenaEvent) serverEventImpl() {}
func (obj ServerArenaEvent) MarshalJSON() ([]byte, error) {
    var raw struct {
		ServerEventType ServerEventType `json:"serverevent_type"`
        ArenaMessage ArenaEvent `json:"arena_message"`
	}

    raw.ServerEventType = SERVERARENAEVENT
    raw.ArenaMessage = obj.ArenaMessage

    return json.Marshal(raw)
}

func (obj ServerArenaEvent) UnmarshalJSON(rawData []byte) error {
    var raw struct {
        ServerEventType ServerEventType `json:"serverevent_type"`
        ArenaMessage ArenaEventUnpacker `json:"arena_message"`
	}

	err := json.Unmarshal(rawData, &raw)

    return err
}


func (msg *ServerEventUnpacker) Uncover() ServerEvent {
	return msg.ServerEvent
}

func (msg *ServerEventUnpacker) UnmarshalJSON(rawData []byte) error {
	var raw struct {
		ServerEventType ServerEventType `json:"serverevent_type"`
	}

	if err := json.Unmarshal(rawData, &raw); err != nil {
		return err
	}

	switch raw.ServerEventType {
	case SERVERARENAEVENT:
		message := ServerArenaEvent{}
		err := json.Unmarshal(rawData, &message)
		if err != nil {
			return err
		}
		msg.ServerEvent = message
	default:
		return fmt.Errorf("unexpected type: %#v", raw.ServerEventType)
	}
	return nil
}

type ServerEventHandler[T any, E any] interface {
    HandleServerArenaEvent(ServerArenaEvent, E) (T, error)
}

func ServerEventDecode[T any, E any](handler ServerEventHandler[T, E], data ServerEvent, extraData E) (ret T, err error) {
	switch v := data.(type) {
    case ServerArenaEvent:
        return handler.HandleServerArenaEvent(v, extraData)
	default:
		return ret, fmt.Errorf("unexpected type: %#v", data)
	}
}
