// Code generated by "stringer -type=ServerEventType"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SERVERARENAEVENT-0]
}

const _ServerEventType_name = "SERVERARENAEVENT"

var _ServerEventType_index = [...]uint8{0, 16}

func (i ServerEventType) String() string {
	if i >= ServerEventType(len(_ServerEventType_index)-1) {
		return "ServerEventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ServerEventType_name[_ServerEventType_index[i]:_ServerEventType_index[i+1]]
}
