// Code generated by go generate; DO NOT EDIT.
package core

import (
    "encoding/json"
    "fmt"
    "time"
)

type ServerResponseType uint8

type ServerResponseUnpacker struct {
    ServerResponse
}

const (
	GENERICRESPONSE ServerResponseType = iota
	LISTARENASRESPONSE ServerResponseType = iota
	ARENAINFORESPONSE ServerResponseType = iota
)
func (GenericResponse) serverResponseImpl() {}
func (obj GenericResponse) MarshalJSON() ([]byte, error) {
    var raw struct {
		ServerResponseType ServerResponseType `json:"serverresponse_type"`
        Success bool `json:"success"`
        FailReason string `json:"fail_reason"`
	}

    raw.ServerResponseType = GENERICRESPONSE
    raw.Success = obj.Success
    raw.FailReason = obj.FailReason

    return json.Marshal(raw)
}

func (ListArenasResponse) serverResponseImpl() {}
func (obj ListArenasResponse) MarshalJSON() ([]byte, error) {
    var raw struct {
		ServerResponseType ServerResponseType `json:"serverresponse_type"`
        Success bool `json:"success"`
        ArenaList []string `json:"arena_list"`
	}

    raw.ServerResponseType = LISTARENASRESPONSE
    raw.Success = obj.Success
    raw.ArenaList = obj.ArenaList

    return json.Marshal(raw)
}

func (ArenaInfoResponse) serverResponseImpl() {}
func (obj ArenaInfoResponse) MarshalJSON() ([]byte, error) {
    var raw struct {
		ServerResponseType ServerResponseType `json:"serverresponse_type"`
        Success bool `json:"success"`
        Name string `json:"name"`
        Agents []AgentInfo `json:"agents"`
        GameStarted bool `json:"game_started"`
        DateCreated time.Time `json:"date_created"`
	}

    raw.ServerResponseType = ARENAINFORESPONSE
    raw.Success = obj.Success
    raw.Name = obj.Name
    raw.Agents = obj.Agents
    raw.GameStarted = obj.GameStarted
    raw.DateCreated = obj.DateCreated

    return json.Marshal(raw)
}


func (msg *ServerResponseUnpacker) Uncover() ServerResponse {
	return msg.ServerResponse
}

func (msg *ServerResponseUnpacker) UnmarshalJSON(rawData []byte) error {
	var raw struct {
		ServerResponseType ServerResponseType `json:"serverresponse_type"`
	}

	if err := json.Unmarshal(rawData, &raw); err != nil {
		return err
	}

	switch raw.ServerResponseType {
	case GENERICRESPONSE:
		message := GenericResponse{}
		err := json.Unmarshal(rawData, &message)
		if err != nil {
			return err
		}
		msg.ServerResponse = message
	case LISTARENASRESPONSE:
		message := ListArenasResponse{}
		err := json.Unmarshal(rawData, &message)
		if err != nil {
			return err
		}
		msg.ServerResponse = message
	case ARENAINFORESPONSE:
		message := ArenaInfoResponse{}
		err := json.Unmarshal(rawData, &message)
		if err != nil {
			return err
		}
		msg.ServerResponse = message
	default:
		return fmt.Errorf("unexpected type: %#v", raw.ServerResponseType)
	}
	return nil
}

type ServerResponseHandler[T any, E any] interface {
    HandleGenericResponse(GenericResponse, E) (T, error)
    HandleListArenasResponse(ListArenasResponse, E) (T, error)
    HandleArenaInfoResponse(ArenaInfoResponse, E) (T, error)
}

func ServerResponseDecode[T any, E any](handler ServerResponseHandler[T, E], data ServerResponse, extraData E) (ret T, err error) {
	switch v := data.(type) {
    case GenericResponse:
        return handler.HandleGenericResponse(v, extraData)
    case ListArenasResponse:
        return handler.HandleListArenasResponse(v, extraData)
    case ArenaInfoResponse:
        return handler.HandleArenaInfoResponse(v, extraData)
	default:
		return ret, fmt.Errorf("unexpected type: %#v", data)
	}
}
