// Code generated by "stringer -type=TransitionType"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GAME_START_TRANSITION-8]
	_ = x[DRAW_TRANSITION-16]
	_ = x[TOSS_TRANSITION-24]
	_ = x[COMPUTE_NAKI_TRANSITION-32]
	_ = x[NAKI_CALLED_TRANSITION-40]
	_ = x[AWAITING_DISCARD_TRANSITION-48]
	_ = x[NO_NAKI_TRANSITION-56]
	_ = x[GAME_FINISHED_TRANSITION-64]
}

const (
	_TransitionType_name_0 = "GAME_START_TRANSITION"
	_TransitionType_name_1 = "DRAW_TRANSITION"
	_TransitionType_name_2 = "TOSS_TRANSITION"
	_TransitionType_name_3 = "COMPUTE_NAKI_TRANSITION"
	_TransitionType_name_4 = "NAKI_CALLED_TRANSITION"
	_TransitionType_name_5 = "AWAITING_DISCARD_TRANSITION"
	_TransitionType_name_6 = "NO_NAKI_TRANSITION"
	_TransitionType_name_7 = "GAME_FINISHED_TRANSITION"
)

func (i TransitionType) String() string {
	switch {
	case i == 8:
		return _TransitionType_name_0
	case i == 16:
		return _TransitionType_name_1
	case i == 24:
		return _TransitionType_name_2
	case i == 32:
		return _TransitionType_name_3
	case i == 40:
		return _TransitionType_name_4
	case i == 48:
		return _TransitionType_name_5
	case i == 56:
		return _TransitionType_name_6
	case i == 64:
		return _TransitionType_name_7
	default:
		return "TransitionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
