// Code generated by "stringer -type=TurnType"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[INVALID-0]
	_ = x[OUT_OF_GAME-1]
	_ = x[IN_GAME-2]
	_ = x[AWAITING_DISCARD-3]
	_ = x[DISCARDED-4]
	_ = x[AWAITING_NAKI-5]
	_ = x[NAKI_CALLED-6]
	_ = x[NAKI_FINISHED-7]
}

const _TurnType_name = "INVALIDOUT_OF_GAMEIN_GAMEAWAITING_DISCARDDISCARDEDAWAITING_NAKINAKI_CALLEDNAKI_FINISHED"

var _TurnType_index = [...]uint8{0, 7, 18, 25, 41, 50, 63, 74, 87}

func (i TurnType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TurnType_index)-1 {
		return "TurnType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TurnType_name[_TurnType_index[idx]:_TurnType_index[idx+1]]
}
